FucoMicro.Web/Controllers/CouponController.cs
using FucoMicro.Web.Models;
using FucoMicro.Web.Service.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FucoMicro.Web.Controllers
{
	public class CouponController : Controller
	{
		private readonly ICouponService _couponService;

		public CouponController(ICouponService couponService)
		{
			_couponService = couponService;
		}

		public async Task<IActionResult> CouponIndex()
		{
			List<CouponDto>? list = new();
			ResponseDto? responseDto = await _couponService.GetAllCouponsAsync();
			if (responseDto != null && responseDto.IsSuccess)
			{
				list = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(responseDto.Result));
			}
			else
			{
				TempData["error"] = responseDto?.Message;
			}

			return View(list);
		}

		public async Task<IActionResult> CouponCreate()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> CouponCreate(CouponDto couponDto)
		{
			if (ModelState.IsValid)
			{
				ResponseDto? responseDto = await _couponService.CreateCouponAsync(couponDto);
				if(responseDto != null && responseDto.IsSuccess)
				{
                    TempData["success"] = responseDto?.Message;
                    return RedirectToAction(nameof(CouponIndex));
				}
                else
                {
                    TempData["error"] = responseDto?.Message;
                }
            }
			return View(couponDto);
		}

		//[HttpPost]
		//public async Task<IActionResult> CouponUpdate(CouponDto couponDto)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		ResponseDto? responseDto = await _couponService.UpdateCouponAsync(couponDto);
		//		if (responseDto != null && responseDto.IsSuccess)
		//		{
  //                  TempData["success"] = responseDto?.Message;
  //                  return RedirectToAction(nameof(CouponIndex));
		//		}
  //              else
  //              {
  //                  TempData["error"] = responseDto?.Message;
  //              }
  //          }
		//	return View(couponDto);
		//}

		public async Task<IActionResult> CouponDelete(int couponId)
		{
			ResponseDto? response = await _couponService.GetCouponByIdAsync(couponId);
			if (response != null && response.IsSuccess)
			{
                CouponDto model = JsonConvert.DeserializeObject<CouponDto>(Convert.ToString(response.Result));
                return View(model);
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return NotFound();
        }

		[HttpPost, ActionName("CouponDelete")]
        public async Task<IActionResult> CouponDeletePost(CouponDto couponDto)
        {
            ResponseDto? response = await _couponService.DeleteCouponAsync(couponDto.CouponId);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = response?.Message;
                return RedirectToAction(nameof(CouponIndex));
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return View(couponDto);
        }
    }
}

FucoMicro.Web/Views/Coupon/CouponCreate.cshtml
@model CouponDto

<form asp-action="CouponCreate" method="post">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Create Coupon</h1>

        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Coupon Code</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="CouponCode" class="form-control" />
                <span asp-validation-for="CouponCode" class="text-danger"></span> 
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Discount Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="DiscountAmount" class="form-control" />
                <span asp-validation-for="DiscountAmount" class="text-danger"></span> 
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Minimum Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="MinAmount" class="form-control" />
                <span asp-validation-for="MinAmount" class="text-danger"></span>
            </div>

            <div class="col-5 offset-2">

                <a class="btn-primary btn form-control" asp-action="CouponIndex">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
        <div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

FucoMicro.Web/Views/Coupon/CouponDelete.cshtml
@model CouponDto

<form asp-action="CouponDelete" method="post">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Delete Coupon</h1>
        <input asp-for="CouponId" hidden />
        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Coupon Code</label>
            </div>
            <div class="col-10 pb-3">
                <input disabled asp-for="CouponCode" class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Discount Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input disabled asp-for="DiscountAmount" class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Minimum Amount</label>
            </div>
            <div class="col-10 pb-3">
                <input disabled asp-for="MinAmount" class="form-control" />
            </div>

            <div class="col-5 offset-2">

                <a class="btn-primary btn form-control" asp-action="CouponIndex">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>
        </div>
        <div>
        </div>
    </div>
</form>

FucoMicro.Web/Views/Coupon/CouponIndex.cshtml
@model IEnumerable<CouponDto>


<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white">Coupons List</h1>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a asp-action="CouponCreate" class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Create New Coupon</a>

			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>
						Coupon Code
					</th>
					<th>
						Discount Amount
					</th>
					<th>
						Minimum Amount
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach(var item in Model)
				{
					<tr>
						<td>
							@item.CouponCode
						</td>
						<td>
							@item.DiscountAmount.ToString("c")
						</td>
						<td>
							@item.MinAmount.ToString("c")
						</td>
						<td>
							<a asp-controller="Coupon" asp-action="CouponDelete" asp-route-couponId="@item.CouponId" class="btn btn-danger">
								<i class="bi bi-trash"></i>
							</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>